language: bash

install: make

services:
  - docker

before_script:
  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build:
  script: make build-all
  on:
    tags: true
    all_branches: true

deploy:
  script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  script: make push-all
  on:
    branch: master
