#!/bin/bash

ROOT_DIR=$(pwd)
cd $ROOT_DIR

function download_hadoop {
    HAS_HADOOP=$(ls $ROOT_DIR/distro | grep -v spark | grep hadoop)
    if [ -z $HAS_HADOOP ]; then
        echo "downloading hadoop-2.7.7"
        # cd $ROOT_DIR/distro
        curl -L -o distro/hadoop-2.7.7.tar.gz https://archive.apache.org/dist/hadoop/common/hadoop-2.7.7/hadoop-2.7.7.tar.gz
    fi
}

function download_hbase {
    HAS_HBASE=$(ls $ROOT_DIR/distro | grep hbase)
    if [ -z $HAS_HBASE ]; then
        echo "downloading hbase-2.1.5"
        cd $ROOT_DIR/distro
        curl -L -O http://archive.apache.org/dist/hbase/2.1.5/hbase-2.1.5-bin.tar.gz
    fi
}

function download_spark {
    HAS_SPARK=$(ls $ROOT_DIR/distro | grep spark)
    if [ -z $HAS_SPARK ]; then
        echo "downloading spark-2.4.7"
        cd $ROOT_DIR/distro
        curl -L -O https://apache.osuosl.org/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
    fi
}

function clean_distro_dir {
    CLEANUP=$(find distro  -mindepth 1 -not -name ".*") # leave the .gitsave file...
    for ARTIFACT in $CLEANUP; do
        rm -r $ARTIFACT
    done
}

clean_distro_dir

while [ "$#" -gt 0 ]; do
  case "$1" in
    --clean) clean_distro_dir; exit 0;;
    --hadoop) download_hadoop; exit 0;;
    --hbase) download_hbase; exit 0;;
    --spark) download_spark; exit 0;;
    *) echo "command not recognized"; exit 1;;
  esac
done

cd $ROOT_DIR