version: "3.7"
services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    image: reynoldsm88/spark-master:latest
    ports:
      - "7077:7077"
      - "8080:8080"
      - "6066:6066"
    volumes:
       - ../../data/spark-master:/opt/app/data
    networks:
      - magi

  spark-worker:
    container_name: spark-worker-1
    hostname: spark-worker-1
    image: reynoldsm88/spark-worker:latest
    environment:
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7078:7078"
      - "8081:8081"
    volumes:
       - ../../data/spark-worker-1:/opt/app/data
    depends_on:
      - spark-master
    networks:
      - magi

networks:
  magi: