version: "3.7"

x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '1m'
      max-file: '5'

services:

  hbase-master:
    <<: *defaults
    container_name: hbase-master
    hostname: hbase-master
    image: magiplatform/hbase-master:latest
    ports:
      - "6022:22"
      - "60000:60000"
      - "60010:60010"
      - "2889:2888"
      - "8085:8085"
    healthcheck:
      test: [ "CMD", "/opt/hbase/bin/healtcheck-master.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    depends_on:
      - hdfs-namenode
      - hdfs-datanode-1
      - hdfs-datanode-2
      - zookeeper
    networks:
      - magi

  hbase-regionserver-1:
    <<: *defaults
    container_name: hbase-regionserver-1
    hostname: hbase-regionserver-1
    image: magiplatform/hbase-regionserver:latest
    ports:
      - "6023:22"
      - "60020:60020"
      - "60030:60030"
      - "2890:2888"
    healthcheck:
      test: [ "CMD", "/opt/hbase/bin/healtcheck-regionserver.sh" ]
      interval: 20s
      start_period: 30s
    depends_on:
      - hdfs-namenode
      - hdfs-datanode-1
      - hdfs-datanode-2
      - hbase-master
      - zookeeper
    networks:
      - magi  

  hbase-regionserver-2:
    <<: *defaults
    container_name: hbase-regionserver-2
    hostname: hbase-regionserver-2
    image: magiplatform/hbase-regionserver:latest
    ports:
      - "6024:22"
      - "60021:60020"
      - "60031:60030"
      - "2891:2888"
    healthcheck:
      test: [ "CMD", "/opt/hbase/bin/healtcheck-regionserver.sh" ]
      interval: 20s
      start_period: 30s
    depends_on:
      - hdfs-namenode
      - hdfs-datanode-1
      - hdfs-datanode-2
      - hbase-master
      - zookeeper
    networks:
      - magi

  hdfs-namenode:
    <<: *defaults
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    image: magiplatform/hdfs-namenode:latest
    ports:
      - "9000:9000"
      - "50070:50070"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-namenode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    volumes:
       - ../../data/hdfs-namenode:/opt/app/data/namenode
    networks:
      - magi

  hdfs-datanode-1:
    <<: *defaults
    container_name: hdfs-datanode-1
    hostname: hdfs-datanode-1
    image: magiplatform/hdfs-datanode:latest
    ports:
      - "50075:50075"
      - "50475:50475"
      - "50010:50010" 
      - "50020:50020"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-datanode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-1:/opt/app/data/datanode
    networks:
      - magi

  hdfs-datanode-2:
    <<: *defaults
    container_name: hdfs-datanode-2
    hostname: hdfs-datanode-2
    image: magiplatform/hdfs-datanode:latest
    ports:
      - "50076:50075"
      - "50476:50475"
      - "50011:50010"
      - "50021:50020"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-datanode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-2:/opt/app/data/datanode
    networks:
      - magi

  zookeeper:
    <<: *defaults
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
      - "3888:3888"
      - "2888:2888"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ../../data/zookeeper-1-data:/data
      - ../../data/zookeeper-1-datalog:/datalog
    networks:
      - magi

networks:
  magi:
