version: "3.7"
services:
  hdfs-namenode:
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    image: reynoldsm88/hdfs-namenode:latest
    ports:
      - "9000:9000"
      - "50070:50070"
    volumes:
       - ../../data/hdfs-namenode:/opt/app/data/namenode
    networks:
      - magi
  
  hdfs-datanode-1:
    container_name: hdfs-datanode-1
    hostname: hdfs-datanode-1
    image: reynoldsm88/hdfs-datanode:latest
    ports:
      - "50075:50075"
      - "50475:50475"
      - "50010:50010" 
      - "50020:50020"
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-1:/opt/app/data/datanode
    networks:
      - magi

  hdfs-datanode-2:
    container_name: hdfs-datanode-2
    hostname: hdfs-datanode-2
    image: reynoldsm88/hdfs-datanode:latest
    ports:
      - "50076:50075"
      - "50476:50475"
      - "50011:50010"
      - "50021:50020"
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-2:/opt/app/data/datanode
    networks:
      - magi

networks:
  magi: