version: "3.7"

x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '1m'
      max-file: '5'

services:
  hdfs-namenode:
    <<: *defaults
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    image: magiplatform/hdfs-namenode:latest
    ports:
      - "9000:9000"
      - "50070:50070"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-namenode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    volumes:
       - ../../data/hdfs-namenode:/opt/app/data/namenode
    networks:
      - magi
  
  hdfs-datanode-1:
    <<: *defaults
    container_name: hdfs-datanode-1
    hostname: hdfs-datanode-1
    image: magiplatform/hdfs-datanode:latest
    ports:
      - "50075:50075"
      - "50475:50475"
      - "50010:50010" 
      - "50020:50020"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-datanode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-1:/opt/app/data/datanode
    networks:
      - magi

  hdfs-datanode-2:
    <<: *defaults
    container_name: hdfs-datanode-2
    hostname: hdfs-datanode-2
    image: magiplatform/hdfs-datanode:latest
    ports:
      - "50076:50075"
      - "50476:50475"
      - "50011:50010"
      - "50021:50020"
    healthcheck:
      test: [ "CMD", "/opt/hadoop/bin/healtcheck-datanode.sh" ]
      interval: 20s
      start_period: 30s
      retries: 5
    depends_on:
      - hdfs-namenode
    volumes:
       - ../../data/hdfs-datanode-2:/opt/app/data/datanode
    networks:
      - magi

networks:
  magi: