version: "3"
services:
  hdfs-namenode:
    container_name: namenode
    hostname: namenode
    image: reynoldsm88/hdfs-namenode:latest
    ports:
      - "9000:9000"
      - "50070:50070"
      - "50470:50470"
    networks:
      - magi
  
  hdfs-datanode:
    container_name: datanode-1
    hostname: datanode-1
    image: reynoldsm88/hdfs-datanode:latest
    ports:
      - "50075:50075"
      - "50475:50475"
      - "50010:50010" 
      - "50020:50020"
    networks:
      - magi

networks:
  magi: