name: build-only
on:
  pull_request:

jobs:
  build-only:
    name: build-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://magiplatform/image-builder:latest
      with:
        entrypoint: make build-all