name: build-only
on:
  pull_request:

jobs:
  build-only:
    name: build-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install --assume-yes make
      - run: sudo apt-get install --assume-yes docker
      - run: make build-all
